HillRange\Security\Entity\Page:
    type: entity
    table: page
    repositoryClass: HillRange\Security\Repository\PageRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [route]
            errorPath: route
            message: 'page.route.unique'
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        route:
            type: string
            length: '100'
            unique: true
        path:
            type: string
            length: '200'
        roles:
            type: array
        cacheTime:
            type: datetime
            nullable: true
        lastModified:
            type: datetime
            column: last_modified
        createdOn:
            type: datetime
            column: created_on
    manyToOne:
        createdBy:
            targetEntity: HillRange\Security\Entity\User
            joinColumn:
                name: created_by
                referencedColumnName: id
        modifiedBy:
            targetEntity: HillRange\Security\Entity\User
            joinColumn:
                name: modified_by
                referencedColumnName: id
