Hillrange\Security\Entity\User:
    type: entity
    table: hrs_user
    repositoryClass: Hillrange\Security\Repository\UserRepository
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [username]
            errorPath: username
            message: 'The User Name must be unique.'
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [email]
            errorPath: email
            message: 'The EMail must be unique.'
    indexes:
        username:
            columns: [ username ] 
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 64
            unique: true
        usernameCanonical:
            type: string
            length: 64
            unique: true
            column: username_canonical
        email:
            type: string
            length: 64
            unique: true
        emailCanonical:
            type: string
            length: 64
            unique: true       
            column: email_canonical
        enabled:
            type: boolean
            options:
                default: '1'
        locale:
            type: string
            length: 10
            nullable: true
        password:
            type: string
            length: 64 
        lastLogin:
            column: last_login
            type: datetime
            nullable: true
        expired:
            type: boolean
            options:
                default: '0'
        expiresAt:
            column: expires_at
            type: datetime
            nullable: true
        confirmationToken:
            type: string
            column: confirmation_token
            nullable: true 
        passwordRequestedAt:
            column: password_requested_at
            type: datetime
            nullable: true
        credentialsExpired:
            type: boolean 
            column: credentials_expired
            options:
                default: '0'
        credentialsExpireAt:
            column: credentials_expire_at
            type: datetime
            nullable: true
        groups:
            type: array
            nullable: true
        directroles:
            type: array
            nullable: true
            column: direct_roles
        userSettings:
            type: array
            column: user_settings
            nullable: true
    lifecycleCallbacks:
        prePersist:
            - checkCanonical
        preUpdate:
            - checkCanonical
