services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    Hillrange\Security\:
        resource: "../../"
        exclude: "../../{Entity,Tests,Exposed}"

    Hillrange\Security\Controller\:
        resource: '../../Controller/'
        tags: ['controller.service_arguments']

    Hillrange\Security\Exposed\:
        resource: '../../Exposed/'
        public: true

    Hillrange\Security\Entity\User:
        arguments:
            - '@Hillrange\Security\Util\ParameterInjector'
    Hillrange\Security\Exposed\LoginSuccessHandler:
        arguments:
            - '@security.http_utils'          # http_utils cannot be auto-wired.
            - '@doctrine.orm.default_entity_manager'
            - '@security.token_storage'
            - '@security.authentication_utils'
            - '@monolog.logger.security'
            - '@router'
            - '@Hillrange\Security\Util\ParameterInjector'
    Hillrange\Security\Exposed\LoginSubscriber:
        arguments:
            - '@security.firewall.map.config.main'
    Hillrange\Security\Exposed\UserFieldsListener:
        tags:
            - { name: doctrine.event_subscriber }
    Hillrange\Security\Exposed\UserTrackListener:
        arguments:
            - '@security.token_storage'
        tags:
            - { name: doctrine.event_listener, event: prePersist, priority: -512 }
            - { name: doctrine.event_listener, event: preUpdate, priority: -512 }
