services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    Hillrange\Security\:
        resource: "../../"
        exclude: "../../{Entity,Tests,Listener,Form,Extension,Voter}"

    Hillrange\Security\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Hillrange\Security\Listener\PageListener:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@service_container'
        tags: { name: 'kernel.event_subscriber', priority: '16' }

    Hillrange\Security\Listener\UserFieldsListener:
        tags:
            - { name: doctrine.event_subscriber }

    Hillrange\Security\Listener\UserTrackListener:
        arguments:
            - '@security.token_storage'
            - '@request_stack'
        tags:
            - { name: doctrine.event_subscriber, event: prePersist, priority: -512 }
            - { name: doctrine.event_subscriber, event: preUpdate, priority: -512 }
        public: true
    hillrange.security.form.login_type:
        class: Hillrange\Security\Form\LoginType
        arguments:
            - '@security.firewall.map.config.main'
        tags:
            - { name: form.type }
    Hillrange\Security\Extension\SecurityExtension:
        arguments:
            - '%security.routes%'
        tags:
            - { name: twig.extension }
    Hillrange\Security\Listener\SuccessHandler:
        arguments:
            - '@security.http_utils'
            - '@doctrine.orm.default_entity_manager'
            - '@security.token_storage'
            - '@security.authentication_utils'
            - '@monolog.logger.security'
            - '@router'
            - '%security.routes%'
    Hillrange\Security\Listener\SecuritySubscriber:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@security.authentication_utils'
            - '@request_stack'
            - '@monolog.logger.security'
        tags: { name: 'kernel.event_subscriber', priority: '-16' }
    hillrange.security.util.user_provider:
        class: Hillrange\Security\Util\UserProvider
        arguments:
            - '@Hillrange\Security\Repository\UserRepository'
            - '%security.hierarchy.roles%'
            - '%security.groups%'
    Hillrange\Security\Entity\User:
        arguments:
            - '%security.hierarchy.roles%'
            - '%security.groups%'
    Hillrange\Security\Voter\GroupVoter:
        arguments:
            - '%security.groups%'
            - 'ROLE_'
        tags:
            - { name: security.voter, priority: 512 }
    hillrange.security.form.direct_role_type:
        class: Hillrange\Security\Form\DirectRoleType
        arguments:
            - '%security.role_hierarchy.roles%'
        tags:
            - { name: form.type }
    hillrange.security.form.group_type:
        class: Hillrange\Security\Form\GroupType
        arguments:
            - '%security.groups%'
        tags:
            - { name: form.type }
    Hillrange\Security\Voter\CurrentUserVoter:
        tags:
            - { name: security.voter, priority: -32 }
