<?php
namespace Hillrange\Security\Repository;

use Hillrange\Security\Entity\Page;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Component\Routing\RouterInterface;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends ServiceEntityRepository
{

	/**
	 * PageRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, Page::class);
	}

	/**
	 * @param $routeName
	 *
	 * @return Page
	 */
	public function loadOneByRoute(string $routeName = null, array $params = []): ?Page
	{
		if (! $routeName)
			return null;

		$page = $this->createQueryBuilder('p')
			->where('p.route = :route')
			->setParameter('route', $routeName)
			->getQuery()
			->getOneOrNullResult();

		if (empty($page))
		{
			$page = new Page();
			$page->setRoute($routeName);
		}

		return $page;
	}
}
