<?php
namespace Hillrange\Security\Repository;

use Hillrange\Security\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ServiceEntityRepository implements UserLoaderInterface
{
	/**
	 * UserRepository constructor.
	 *
	 * @param RegistryInterface $registry
	 */
	public function __construct(RegistryInterface $registry)
	{
		parent::__construct($registry, User::class);
	}

	/**
	 * @param $username
	 *
	 * @return null|UserInterface
	 */
	public function loadUserByUsername($username): ?UserInterface
	{
		return $this->createQueryBuilder('u')
			->where('(u.username = :username OR u.email = :email)')
			->setParameter('username', $username)
			->setParameter('email', $username)
			->getQuery()
			->getOneOrNullResult();
	}

	/**
	 * @param $token
	 *
	 * @return null|UserInterface
	 */
	public function loadUserByToken($token): ?UserInterface
	{
		return $this->createQueryBuilder('u')
			->where('u.confirmationToken = :token')
			->setParameter('token', $token)
			->getQuery()
			->getOneOrNullResult();
	}
}
