Hillrange\Security\Entity\User:
    constraints:
        - HillrangeSecurity\Validator\UniqueOrBlank:
            fields: [username]
            errorPath: username
            message: user.error.username.unique
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            errorPath: email
            message: user.error.email.unique
    properties:
        email:
            - Email: 
                message: user.error.email.email
                checkMX: true
            - NotBlank:
        locale:
            - Locale: ~
        password:
            - NotBlank: ~